### ISSUE TITLE
Remove requirement for frames.bin

### ISSUE THREAD

**Issue by krisfur** [DUNE-DAQ/integrationtest#9]
It would be beneficial to allow for running integration tests without having to specify a frame file, for tests that do not incorporate one.

**Comment by philiprodrigues** [comment]
I agree. This is a bit of a mistake in the way I have things set up. I think the right solution is to move the requirement for specifying frame files into a `conftest.py`  as (partially) described here:

https://docs.pytest.org/en/6.2.x/example/simple.html

I had things set up like this initially, but switched to the current setup because it saves test writers having to create a `conftest.py`. In hindsight, that was probably the wrong choice for the reason you've pointed out, so we should switch back.
